require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::SponsorsController do

  # This should return the minimal set of attributes required to create a valid
  # Sponsor. As you add validations to Sponsor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => "sponsor", :event_id => "1"}
  end

  describe "GET index" do
    it "assigns all sponsors as @sponsors" do
      sponsor = Sponsor.create! valid_attributes
      get :index
      assigns(:sponsors).should eq([sponsor])
    end
  end

  describe "GET show" do
    it "assigns the requested sponsor as @sponsor" do
      sponsor = Sponsor.create! valid_attributes
      get :show, :id => sponsor.id.to_s
      assigns(:sponsor).should eq(sponsor)
    end
  end

  describe "GET new" do
    it "assigns a new sponsor as @sponsor" do
      get :new
      assigns(:sponsor).should be_a_new(Sponsor)
    end
  end

  describe "GET edit" do
    it "assigns the requested sponsor as @sponsor" do
      sponsor = Sponsor.create! valid_attributes
      get :edit, :id => sponsor.id.to_s
      assigns(:sponsor).should eq(sponsor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sponsor" do
        expect {
          post :create, :sponsor => valid_attributes
        }.to change(Sponsor, :count).by(1)
      end

      it "assigns a newly created sponsor as @sponsor" do
        post :create, :sponsor => valid_attributes
        assigns(:sponsor).should be_a(Sponsor)
        assigns(:sponsor).should be_persisted
      end

      it "redirects to the created sponsor" do
        post :create, :sponsor => valid_attributes
        response.should redirect_to(Sponsor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sponsor as @sponsor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sponsor.any_instance.stub(:save).and_return(false)
        post :create, :sponsor => {}
        assigns(:sponsor).should be_a_new(Sponsor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sponsor.any_instance.stub(:save).and_return(false)
        post :create, :sponsor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sponsor" do
        sponsor = Sponsor.create! valid_attributes
        # Assuming there are no other sponsors in the database, this
        # specifies that the Sponsor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sponsor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sponsor.id, :sponsor => {'these' => 'params'}
      end

      it "assigns the requested sponsor as @sponsor" do
        sponsor = Sponsor.create! valid_attributes
        put :update, :id => sponsor.id, :sponsor => valid_attributes
        assigns(:sponsor).should eq(sponsor)
      end

      it "redirects to the sponsor" do
        sponsor = Sponsor.create! valid_attributes
        put :update, :id => sponsor.id, :sponsor => valid_attributes
        response.should redirect_to(sponsor)
      end
    end

    describe "with invalid params" do
      it "assigns the sponsor as @sponsor" do
        sponsor = Sponsor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sponsor.any_instance.stub(:save).and_return(false)
        put :update, :id => sponsor.id.to_s, :sponsor => {}
        assigns(:sponsor).should eq(sponsor)
      end

      it "re-renders the 'edit' template" do
        sponsor = Sponsor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sponsor.any_instance.stub(:save).and_return(false)
        put :update, :id => sponsor.id.to_s, :sponsor => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sponsor" do
      sponsor = Sponsor.create! valid_attributes
      expect {
        delete :destroy, :id => sponsor.id.to_s
      }.to change(Sponsor, :count).by(-1)
    end

    it "redirects to the sponsors list" do
      sponsor = Sponsor.create! valid_attributes
      delete :destroy, :id => sponsor.id.to_s
      response.should redirect_to(sponsors_url)
    end
  end

end
